version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /bacterial_genome_assembly.ga
  testParameterFiles:
  - /bacterial_genome_assembly-tests.yml
  authors:
  - name: abromics-consortium
    url: https://www.abromics.fr/
  - name: ABRomics
    email: abromics-support@groupes.france-bioinformatique.fr
  - name: Pierre Marin
    alternateName: pimarin
    orcid: 0000-0002-8304-138X
  - name: Clea Siguret
    alternateName: clsiguret
    orcid: 0009-0005-6140-0379
